name: Publisher

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Build
        script: |
          npm install
          gulp build

      - name: Zip Files
        working-directory: ./dist
        run: zip -r ./DrDPlus.zip ./*
    
      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/GetVersion.js)"
      
      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with: 
          allowUpdates: true
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: './DrDPlus.zip'
          tag: ${{ steps.get-version.outputs.version }}
